### PR TITLE
Quick adaptation to vsomeip3 3.1.7

### PR DESCRIPTION
**Pull request by nkh-lab**
Signed-off-by: Nikolay <nkh@ua.fm>

### CODE REVIEW

**Comment by jayhou** [comment]
@nkh-lab I've update vsomeip and libcommonapi libcommonapi-someip to the newest version of my Android device,but when the process startup it killed by signal 1 SIGHUP, have you ever occur this problem? thank you.

**Comment by jayhou** [comment]
@scmikezhang I think so. I compiled success with this patch, and will failed without this patch.

**Comment by nkh-lab** [comment]
> @nkh-lab I've update vsomeip and libcommonapi libcommonapi-someip to the newest version of my Android device,but when the process startup it killed by signal 1 SIGHUP, have you ever occur this problem? thank you.

I don't remember that I had such issue, what does tombstone says about it, any backtrace?  
For now my simple CommonAPI example works well.

**Comment by 007herelsp** [comment]
> On Windows I had to add the following to lines to `Types.hpp`:
> 
> ```c++
> typedef vsomeip::uid_t uid_t;
> typedef vsomeip::gid_t gid_t;
> ```
Thanks for the information, so I'm thinking I don't need to add this code anymore

**Comment by rettenbs** [comment]
> 
> 
> > On Windows I had to add the following to lines to `Types.hpp`:
> > ```c++
> > typedef vsomeip::uid_t uid_t;
> > typedef vsomeip::gid_t gid_t;
> > ```
> 
> Thanks for the information, so I'm thinking I don't need to add this code anymore

You need to accept this pull request: https://github.com/nkh-lab/capicxx-someip-runtime/pull/1

**Comment by nkh-lab** [comment]
Requested pull request [nkh-lab#1](https://github.com/nkh-lab/capicxx-someip-runtime/pull/1) was merged.

**Comment by lutzbichler** [comment]
CommonAPI 3.2 depends on vSomeIP 3.x

**Pull request closed without merging**
